<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>RimTavern</AssemblyName>
    <RootNamespace>RimTavern</RootNamespace>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <OutputPath>..\..\1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
    <Deterministic>true</Deterministic>
    <RestorePackagesPath>$(UserProfile)\.nuget\packages</RestorePackagesPath>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="krafs.rimworld.ref" Version="1.6.4519-beta" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
