using System.Collections.Generic;
using System.Linq;
using RimTavern.Core;
using RimTavern.Data;
using RimTavern.Logic;
using UnityEngine;
using Verse;

namespace RimTavern.UI
{
    /// <summary>
    /// Galgame-style dialogue window (M1):
    /// - transcript log (scroll)
    /// - NPC lines generated by LLM
    /// - protagonist answers via generated option buttons AND an always-visible free text field
    /// - game speed is capped at 1x while the window is open
    /// </summary>
    public class TavernDialogueWindow : Window
    {
        public const string InputControlName = "RimTavernInputField";

        /// <summary>How many Tavern dialogue windows are currently open (used to avoid stacking auto-events).</summary>
        public static int OpenCount { get; private set; }

        private readonly Pawn protagonist;
        private readonly Pawn npc;
        private readonly bool npcInitiated;
        private readonly DialogueSession session;
        private string input = "";
        private bool endAfterSend;
        private Vector2 scrollPos;
        private int lastHistoryCount = -1;
        private TimeSpeed speedBefore = TimeSpeed.Normal;
        private bool forcedSpeedDown;
        private bool focusGiven;

        public TavernDialogueWindow(Pawn protagonist, Pawn npc, bool npcInitiated = false, string eventNote = "", List<string> forceLoreKeys = null)
        {
            this.protagonist = protagonist;
            this.npc = npc;
            this.npcInitiated = npcInitiated;
            this.session = new DialogueSession(protagonist, npc, npcInitiated, eventNote ?? "", forceLoreKeys);

            doCloseX = true;
            draggable = true;
            resizeable = true;
            absorbInputAroundWindow = false;
            preventCameraMotion = false;
            forcePause = false;
            closeOnCancel = true;
            doWindowBackground = false; // translucent look (悬浮窗风格)

            OpenCount++;
            RememberSpeed();
            session.Start();
        }

        public override Vector2 InitialSize
        {
            get { return new Vector2(680f, 540f); }
        }

        public override void PreClose()
        {
            base.PreClose();
            OpenCount--;
            RestoreSpeed();
            RecordArchive();
            session.EndSession();
            session.Dispose();
        }

        /// <summary>Push the finished conversation into the save-archive and the translucent overlay.</summary>
        private void RecordArchive()
        {
            try
            {
                if (session == null || session.History.Count == 0) return;
                int tick = Find.TickManager != null ? Find.TickManager.TicksGame : 0;
                var list = new List<SavedLine>();
                foreach (DialogueLine line in session.History)
                {
                    list.Add(new SavedLine(line.Speaker, line.Text, line.IsNpc));
                }
                RimTavernGameComp.Get()?.ArchiveDialogue(tick, session.ProtagonistName, session.NpcName, list);
                RimTavernGameComp.Get()?.RecordDialogueEnded(npc != null ? npc.thingIDNumber : -1, tick);
                foreach (DialogueLine line in session.History)
                {
                    TavernHistory.Push(line.Speaker, line.Text, line.IsNpc);
                }
            }
            catch (System.Exception ex)
            {
                Log.Warning("[RimTavern] 归档对话失败: " + ex.Message);
            }
        }

        public override void DoWindowContents(Rect inRect)
        {
            session.Tick();

            // translucent backdrop (悬浮窗风格)
            Color bg = GUI.color;
            GUI.color = new Color(0.09f, 0.09f, 0.1f, 0.68f);
            Widgets.DrawBoxSolid(inRect, GUI.color);
            Widgets.DrawBoxSolidWithOutline(inRect, GUI.color, new Color(1f, 1f, 1f, 0.3f), 1);
            GUI.color = bg;

            float pad = 10f;
            Rect area = inRect.ContractedBy(pad);
            float x = area.x;
            float y = area.y;

            // Header
            Text.Font = GameFont.Medium;
            string tag = npcInitiated ? "【事件】" : "";
            Widgets.Label(new Rect(x, y, area.width, 26f), tag + npc.LabelShort + "  ↔  " + protagonist.LabelShort + "（RimTavern）");
            Text.Font = GameFont.Small;
            y += 30f;

            Text.Font = GameFont.Tiny;
            GUI.color = new Color(0.7f, 0.7f, 0.7f);
            Widgets.Label(new Rect(x, y, area.width, 18f), "场景：殖民地一角，两人开始交谈。");
            GUI.color = Color.white;
            Text.Font = GameFont.Small;
            y += 22f;

            float ctrlH = ControlsHeight(area.width);
            Rect logRect = new Rect(x, y, area.width, area.yMax - y - ctrlH);
            DrawLog(logRect);
            y = area.yMax - ctrlH;
            DrawControls(new Rect(x, y, area.width, ctrlH));
        }

        // ---------- speed ----------

        private void RememberSpeed()
        {
            if (Find.TickManager == null) return;
            speedBefore = Find.TickManager.CurTimeSpeed;
            if (!Find.TickManager.Paused && speedBefore > TimeSpeed.Normal)
            {
                Find.TickManager.CurTimeSpeed = TimeSpeed.Normal; // 自动降到 1 速一次，玩家可自行再调
                forcedSpeedDown = true;
            }
        }

        private void RestoreSpeed()
        {
            if (Find.TickManager == null) return;
            // 仅在我们降过速、且玩家之后没有自行改速时，才还原原速度
            if (!Find.TickManager.Paused && forcedSpeedDown
                && Find.TickManager.CurTimeSpeed == TimeSpeed.Normal)
            {
                Find.TickManager.CurTimeSpeed = speedBefore;
            }
            forcedSpeedDown = false;
        }

        // ---------- layout ----------

        private float ControlsHeight(float width)
        {
            switch (session.Stage)
            {
                case TalkStage.Error:
                    return 100f;
                case TalkStage.NpcThinking:
                case TalkStage.OptionsThinking:
                    return 70f; // hint + input row
                case TalkStage.AwaitChoice:
                    return 24f + 30f + 38f + 6f + Mathf.Min(session.Options.Count, 5) * 34f;
                default:
                    return 40f;
            }
        }

        private void DrawControls(Rect r)
        {
            float x = r.x;
            float y = r.y;
            float w = r.width;

            switch (session.Stage)
            {
                case TalkStage.Error:
                {
                    GUI.color = new Color(1f, 0.6f, 0.6f);
                    Widgets.Label(new Rect(x, y, w, 44f), "出错：" + session.ErrorText);
                    GUI.color = Color.white;
                    y += 48f;
                    if (Widgets.ButtonText(new Rect(x, y, 120f, 30f), "重试"))
                    {
                        session.Retry();
                    }
                    if (Widgets.ButtonText(new Rect(x + 130f, y, 120f, 30f), "关闭"))
                    {
                        Close();
                    }
                    return;
                }
                case TalkStage.NpcThinking:
                case TalkStage.OptionsThinking:
                {
                    Widgets.Label(new Rect(x, y, w, 24f), "… " + session.BusyHint);
                    y += 28f;
                    break;
                }
                case TalkStage.AwaitChoice:
                {
                    // Snapshot the option list: PlayerSubmit() clears Options, so never index the
                    // live list after a click in the same frame (fixes ArgumentOutOfRange on pick).
                    var opts = new List<string>(session.Options);
                    int shown = Mathf.Min(opts.Count, 5);
                    bool submitted = false;
                    for (int i = 0; i < shown && !submitted; i++)
                    {
                        string opt = opts[i];
                        Rect or = new Rect(x, y, w, 30f);
                        TooltipHandler.TipRegion(or, opt);
                        if (Widgets.ButtonText(or, "　" + opt + "　"))
                        {
                            SubmitMaybeEnd(opt);
                            submitted = true;
                        }
                        y += 34f;
                    }
                    if (submitted)
                    {
                        return; // stage already changed to thinking; redraw next frame
                    }
                    Widgets.CheckboxLabeled(new Rect(x, y, w, 22f), "发送后结束本段对话（发送完这句就关闭）", ref endAfterSend);
                    y += 24f;
                    if (Widgets.ButtonText(new Rect(x, y, w / 2f - 4f, 28f), "换一批选项"))
                    {
                        session.RegenerateOptions();
                        return;
                    }
                    if (Widgets.ButtonText(new Rect(x + w / 2f + 4f, y, w / 2f - 4f, 28f), "重写对方上一句"))
                    {
                        session.TryRegenerateLastNpc();
                        return;
                    }
                    y += 32f;
                    break;
                }
            }

            // Always-visible free input row
            float sendW = 92f;
            float endW = 84f;
            float gap = 6f;
            float inputW = w - sendW - endW - gap * 2f;
            Rect inputRect = new Rect(x, y, inputW, 32f);
            bool canSend = session.Stage == TalkStage.AwaitChoice;

            GUI.SetNextControlName(InputControlName);
            bool prev = GUI.enabled;
            GUI.enabled = canSend;
            input = Widgets.TextField(inputRect, input);
            GUI.enabled = prev;

            if (canSend && Event.current.isKey && Event.current.keyCode == KeyCode.Return
                && GUI.GetNameOfFocusedControl() == InputControlName && !string.IsNullOrWhiteSpace(input))
            {
                SubmitMaybeEnd(input);
                Event.current.Use();
            }

            if (Widgets.ButtonText(new Rect(inputRect.xMax + gap, y, sendW, 32f), "发送"))
            {
                if (canSend && !string.IsNullOrWhiteSpace(input))
                {
                    SubmitMaybeEnd(input);
                }
            }
            if (Widgets.ButtonText(new Rect(inputRect.xMax + gap + sendW + gap, y, endW, 32f), "结束对话"))
            {
                Close();
            }

            if (!focusGiven)
            {
                focusGiven = true;
                GUI.FocusControl(InputControlName);
            }
        }

        /// <summary>Send the current protagonist line; if "end after send" is checked, close right away.</summary>
        private void SubmitMaybeEnd(string text)
        {
            bool end = endAfterSend;
            if (session.Stage == TalkStage.AwaitChoice)
            {
                session.PlayerSubmit(text);
                input = "";
                if (end)
                {
                    Close();
                }
            }
        }

        private void DrawLog(Rect rect)
        {
            if (rect.height < 30f) return;

            if (session.History.Count != lastHistoryCount)
            {
                lastHistoryCount = session.History.Count;
            }

            float lineWidth = rect.width - 18f;
            float contentH = 4f;
            var lineHeights = new List<float>();
            foreach (DialogueLine line in session.History)
            {
                float h = Text.CalcHeight(line.Text, lineWidth) + 22f; // name row + text + gap
                lineHeights.Add(h);
                contentH += h;
            }

            Widgets.BeginScrollView(rect, ref scrollPos, new Rect(0f, 0f, rect.width - 16f, contentH));
            float y = 4f;
            for (int i = 0; i < session.History.Count; i++)
            {
                DialogueLine line = session.History[i];
                GUI.color = line.IsNpc ? new Color(0.72f, 0.86f, 1f) : new Color(1f, 0.9f, 0.7f);
                Text.Font = GameFont.Small;
                Widgets.Label(new Rect(2f, y, lineWidth, 20f), line.Speaker);
                GUI.color = Color.white;
                Widgets.Label(new Rect(2f, y + 18f, lineWidth, lineHeights[i] - 22f), line.Text);
                y += lineHeights[i];
            }
            Widgets.EndScrollView();

            // Auto-scroll to bottom when a new line arrives.
            if (lastHistoryCount >= 0 && session.History.Count > 0
                && scrollPos.y + rect.height < contentH - 40f)
            {
                scrollPos.y = contentH;
            }
        }
    }
}
